### PR TITLE
Implement `braket.ahs.AnalogHamiltonianSimulation.from_ir()`

### PR DESCRIPTION
**Pull request by king-p3nguin**
*Issue #, if available:*
- #971

*Description of changes:*
- `braket.ahs.AnalogHamiltonianSimulation.from_ir()` was implemented.

*Testing done:*

Input:

```python
from braket.timings.time_series import TimeSeries
from braket.ahs.analog_hamiltonian_simulation import AnalogHamiltonianSimulation
from braket.ahs.atom_arrangement import AtomArrangement
from braket.ahs.atom_arrangement import SiteType
from braket.ahs.driving_field import DrivingField
from braket.ahs.local_detuning import LocalDetuning
from braket.ahs.field import Field
from braket.ahs.pattern import Pattern

register = (
    AtomArrangement()
    .add((0.0, 0.0))
    .add((0.0, 3.0e-6))
    .add((0.0, 6.0e-6))
    .add((3.0e-6, 0.0))
    .add((3.0e-6, 3.0e-6))
    .add((3.0e-6, 3.0e-6), SiteType.VACANT)
    .add((3.0e-6, 6.0e-6), SiteType.VACANT)
)

driving_field = DrivingField(
    TimeSeries().put(0.0, 0.0).put(3.0e-7, 2.51327e7).put(2.7e-6, 2.51327e7).put(3.0e-6, 0.0),
    TimeSeries().put(0.0, 0).put(3.0e-6, 0),
    TimeSeries()
    .put(0.0, -1.25664e8)
    .put(3.0e-7, -1.25664e8)
    .put(2.7e-6, 1.25664e8)
    .put(3.0e-6, 1.25664e8),
)


local_detuning = LocalDetuning(
    Field(
        TimeSeries().put(0.0, -1.25664e8).put(3.0e-6, 1.25664e8),
        Pattern([0.5, 1.0, 0.5, 0.5, 0.5, 0.5]),
    )
)

hamiltonian = driving_field + local_detuning
ahs = AnalogHamiltonianSimulation(register=register, hamiltonian=hamiltonian)

print(ahs.to_ir() == AnalogHamiltonianSimulation.from_ir(ahs.to_ir()).to_ir())
```

Output:
```text
True
```

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by peterkomar-aws — CHANGES_REQUESTED** [review]
Very precise work, thank you for contributing this PR. I highlighted few changes that would make this ready for approval.

**Comment by king-p3nguin** [comment]
@peterkomar-aws Thank you for reviewing! I made the change based on your review.

**Review by peterkomar-aws — DISMISSED** [review]
Only one minor suggestions. Looks good to me. Thanks for the quick turnaround. Great work!

**Comment by peterkomar-aws** [comment]
Hi @king-p3nguin , all tests are passing, there is only a minor test coverage degradation (see the [coverage report](https://github.com/amazon-braket/amazon-braket-sdk-python/pull/983#issuecomment-2152631375)). Can you add a test that covers [L110](https://app.codecov.io/gh/amazon-braket/amazon-braket-sdk-python/pull/983?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=amazon-braket#a91d75a285e78650ea272abac1dd5bba-R110) of the analog_hamiltonian_simulation module?

**Comment by king-p3nguin** [comment]
@peterkomar-aws Thank you for reporting. It seems like the `pattern` in `DrivingField` is always `"uniform"`, so I removed the static method `_field_or_time_series_from_ir()` and just set `TimeSeries` for the `DrivingField`. Let me know if it is okay or not.

**Review by peterkomar-aws — APPROVED** [review]

**Review by shpface — APPROVED** [review]
Nice work. Thanks for the contribution.

**Pull request merged**
