### PR TITLE
update: adding a test to check for circular imports

### PR DESCRIPTION
**Pull request by krneta**
*Issue #, if available:*

*Description of changes:*

*Testing done:*
I reset back to where we had the issue with https://github.com/amazon-braket/amazon-braket-sdk-python/commit/eed59ff40e59075c2ffca7a03ac2db7730892506 change, and then verified that I could detect the issue regardless of the order that the modules were tested in.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by math411** [comment]
Should consistent start methods across OS's be confirmed with https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method

**Comment by krneta** [comment]
> Should consistent start methods across OS's be confirmed with https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method

Do you mean that we should be using spawn on linux? Why? It doesn't seem it would make a difference here?

**Review by kshitijc — APPROVED** [review]
Thanks for this change!

**Comment by krneta** [comment]
> Should consistent start methods across OS's be confirmed with https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method

While talking offline, Abe brought up the point that the parent process could have imports that could carry over to the children with 'fork'. I'm not sure about that, but it seems fairly safe to set them all to 'spawn'.

**Comment by speller26** [comment]
Note: use the prefix `test: `

**Comment by krneta** [comment]
> Note: use the prefix `test: ` for the commit

Sorry, I didn't see this in time.

**Pull request merged**
